# Generates a C source holding every file under ASSETS_DIR as a byte array,
# so the binary carries its fonts and icons and ships as a single file.
# Run in script mode: cmake -DASSETS_DIR=... -DOUTPUT=... -P embed_assets.cmake

file(GLOB_RECURSE files RELATIVE "${ASSETS_DIR}" "${ASSETS_DIR}/*")
list(SORT files)

set(body "/* Generated by cmake/embed_assets.cmake -- do not edit. */\n")
string(APPEND body "#include \"assets.h\"\n\n")

set(index 0)
set(table "")
foreach(name IN LISTS files)
    file(READ "${ASSETS_DIR}/${name}" hex HEX)
    string(LENGTH "${hex}" hex_length)
    math(EXPR size "${hex_length} / 2")

    # 16 bytes per line keeps every line short enough for any compiler.
    string(REGEX REPLACE "([0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f])"
           "\\1\n" hex "${hex}")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")

    string(APPEND body "static const unsigned char asset_${index}[] = {\n${bytes}\n};\n\n")
    string(APPEND table "    {\"${name}\", asset_${index}, ${size}},\n")
    math(EXPR index "${index} + 1")
endforeach()

string(APPEND body "const swapp_asset swapp_assets[] = {\n${table}};\n")
string(APPEND body "const size_t swapp_asset_count = ${index};\n")

# Only touch the output when it changed, so an unrelated reconfigure doesn't
# force a recompile of a multi-megabyte source.
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" previous)
    if(previous STREQUAL body)
        return()
    endif()
endif()
file(WRITE "${OUTPUT}" "${body}")
